# Generated by Django 4.1.7 on 2023-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('direction', models.CharField(choices=[('Back-end', 'Back-end'), ('Front-end', 'Front-end'), ('Fullstack', 'Fullstack'), ('UX/UI', 'UX/UI')], max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=255)),
            ],
        ),
    ]
